### PR TITLE
Cleaning up the longer-term data.

### PR DESCRIPTION
**Pull request by ldecicco-USGS**

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
@dblodgett-usgs ...can you paste the link to that table on the web where we can convert the "a" "b" and "c" remark codes to something more interesting? I've been poking all over the water use page, but can't seem to find it

**Comment by dblodgett-usgs** [comment]
It's in here: http://pubs.usgs.gov/circ/1405/pdf/circ1405.pdf toward the bottom.

Edit: page 51

**Comment by jordansread** [comment]
@ldecicco-USGS did you want to add the codes to this before merge, or is it ready?

**Comment by ldecicco-USGS** [comment]
@aappling-usgs I think you can merge this and then your stacked bars should be a little more complete. Have a look, and merge if it's OK to you. I'll do another PR with the key for what "a" "b" and "c" means.

**Pull request merged**
