### PR TITLE
buttons and svg css

### PR DESCRIPTION
**Pull request by jordansread**

### CODE REVIEW

**Comment by jordansread** [comment]
image

ignore the colors and other things. 

@jiwalker-usgs I will clean up the look of it, but this should have what you need to set the variable for category w/ a click. Calls `setCategory({category}, evt)`

**Comment by jiwalker-usgs** [comment]
Cool, I think I'll take a crack at globalizing the colors as well.

**Comment by aappling-usgs** [comment]
looks pretty. any input needed before merge?

**Comment by jordansread** [comment]
☝️ better category colors if you have 'em

**Comment by aappling-usgs** [comment]
this looks great (ok the colors need work, but overall great). however, i don't see the state shapes. any ideas? i'm using `httd("target")`

image

**Comment by aappling-usgs** [comment]
for colors, we could think about staying consistent with either http://pubs.usgs.gov/fs/2014/3109/pdf/fs2014-3109.pdf page 2
image

or http://pubs.usgs.gov/circ/1405/pdf/circ1405.pdf fig 14 (p 46)
image

**Pull request merged**
