### PR TITLE
Final data updates and cleaning house.

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
The data has been updated in preparation for release. This will require a full rebuild from ScienceBase and the current build will be weird, probably not broken, until this is merged.

I also refactored the data fetch and process viz.yml / file names / function names while deleting things that are no longer needed from the old data we were using.

### CODE REVIEW

**Comment by jordansread** [comment]
```js
map.js?_c=4689679:102 Uncaught TypeError: Cannot read property 'barScale' of undefined(…)
```
looks like something is missing from the json generated by this PR>

**Comment by dblodgett-usgs** [comment]
Latest commit fixes this... 2015 year label was missing.

**Comment by dblodgett-usgs** [comment]
We had to switch 1960 irrigation to read total rather than sw/gw split irrigation withdrawals because the split of sw/gw wasn't published in the 1960 compilation. Subsequent work has estimated the split, but the logic for the split is unpublished.

**Comment by jordansread** [comment]
Check w/ Nancy on the split estimation?

**Comment by dblodgett-usgs** [comment]
That's already been hashed out. I'm just stating the reason for switching to totals here. It's a done deal.

**Pull request merged**
