### PR TITLE
Moving AWUDS to sciencebase

### PR DESCRIPTION
**Pull request by jiwalker-usgs**
When building, user will need sciencebase credentials saved to file.  Handily, there is a function in vizlab to save this for you (needs to be run if you update your password).  Just run `storeSBcreds()` and enter your username and password (note that password is displayed, we should fix this).

### CODE REVIEW

**Comment by jordansread** [comment]
This all set?

**Comment by jiwalker-usgs** [comment]
Yup

**Comment by jiwalker-usgs** [comment]
dev deploy will again break for a bit though (needs creds)

**Comment by jordansread** [comment]
Ok, going to merge this after mine gets merged then. Mine #143 has the legend thing working now

**Pull request merged**
